### ISSUE TITLE
Allow a more flexible reducers configuration

### ISSUE THREAD

**Issue by miraage** [pofigizm/redux-dynamic#6]
When using a certain library, e.g. [redux-persist](https://github.com/rt2zz/redux-persist#basic-usage), there is a need in composing reducers.

There is a code in [reload-state.js](https://github.com/pofigizm/redux-dynamic/blob/e37ae27e618216dd320196455588153980b2f92f/src/reload-state.js#L5) that enforces a POJO reducer.

It would be cool to have smth like:
```js
// app code
import { persistReducer } from 'redux-persist'

const dynamicInstance = createInstance({
  reducer: {
    router: connectRouter(history),
  },
  combineReducers(reducers) {
    return persistReducer(
      {}, // persist config
      combineReducers(reducers),
    )
  },
})

// library code: reload-state.js
const combineFn = registry.combineReducers || combineReducers

store.replaceReducer(combineFn(registry.reducers))
```

**Comment by pofigizm** [comment]
Hello,
thank you for your suggestion.

Currently, I work on new version (https://github.com/pofigizm/redux-dynamic/tree/next). It will have some breaking changes. After that, I will think about your case.
